# Task no. 1: What is FOR loop?

In [11]:
import timeit

limit = pow(10, 25)

def arithmetic_progression_sum(input_value = limit):   
    return (((1 + input_value) / 2) * input_value)

print('example1 is: ', int(arithmetic_progression_sum(1)))
print('example2 is: ', int(arithmetic_progression_sum(3)))
print('example3 is: ', int(arithmetic_progression_sum(10)))
print('limit is: ', int(arithmetic_progression_sum(limit)))
print('limit exec time: ', timeit.timeit(arithmetic_progression_sum, number = 1))

example1 is:  1
example2 is:  6
example3 is:  55
limit is:  50000000000000014199478637615598758708475143913472
limit exec time:  2.100000074278796e-06


# Task no. 2: Counting islands

In [57]:
import numpy as np

matrix_a = np.array([[0, 1, 0],[0, 0, 0],[0, 1, 1]])
matrix_b = np.array([[0, 0, 0, 1],[0, 0, 1, 0],[0, 1, 0, 0]])
matrix_c = np.array([[0, 0, 0, 1],[0, 0, 1, 1],[0, 1, 0, 1]])
matrix_d = np.array([[1, 0, 1, 0],[0, 1, 0, 1],[1, 0, 1, 0]])

def check_for_more_land(matrix_map, rows, columns, row, column):
    if ((row < 0) or (row >= rows) or (column < 0) or (column >= columns) or (matrix_map[row][column] == 0)):
        pass
    else:
        matrix_map[row][column] = 0 # marks as visited

        check_for_more_land(matrix_map, rows, columns, row + 1, column)
        check_for_more_land(matrix_map, rows, columns, row - 1, column)
        check_for_more_land(matrix_map, rows, columns, row, column + 1)
        check_for_more_land(matrix_map, rows, columns, row, column - 1)
    
def count_islands(matrix_map):
    rows, columns = matrix_map.shape
    islands_counter = 0
    map_copy = np.copy(matrix_map)
    for row, x in enumerate(map_copy):
        for column, y in enumerate(x):
            if y == 1:
                check_for_more_land(map_copy, rows, columns, row, column)
                islands_counter += 1
    return islands_counter

print(matrix_a, 'Number of islands is:',count_islands(matrix_a))
print(matrix_b, 'Number of islands is:',count_islands(matrix_b))
print(matrix_c, 'Number of islands is:',count_islands(matrix_c))
print(matrix_d, 'Number of islands is:',count_islands(matrix_d))

    
    

[[0 1 0]
 [0 0 0]
 [0 1 1]] Number of islands is: 2
[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]] Number of islands is: 3
[[0 0 0 1]
 [0 0 1 1]
 [0 1 0 1]] Number of islands is: 2
[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]] Number of islands is: 6
